package com.tcc.projeto.core.domain.entity;

public enum SubCategory {
    CAIXA_E_BANCO,
    APLICACOES_FINANCEIRAS,
    CONTAS_A_RECEBER,
    ESTOQUES,
    OUTROS_CREDITOS,
    REALIZAVEL_A_LONGO_PRAZO,
    IMPOSTO_DE_RENDA_E_CONTRIBUICAO_SOCIAL,
    PROPRIEDADES_PARA_INVESTIMENTO,
    IMOBILIZADO,
    INTANGIVEL,
    EMPRESTIMOS_E_FINANCIAMENTOS,
    ARRENDAMENTOS,
    FORNECEDORES,
    PARTES_RELACIONADAS,
    CAPITAL_SOCIAL,
    RESERVA_DE_CAPITAL,
    RESERVA_DE_LUCROS,
    RESERVA_DE_INVESTIMENTOS_FISCAIS,
    OUTROS_RESULTADOS_ABRANGENTES,
    LUCROS_ACUMULADOS,
    DIVIDENTES_ADICIONAIS_PROPOSTOS
}
